# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ktEds2NOFLKhvcUFnKTUZZidwhzePiOq
"""

!pip install -q streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import joblib
# 
# # Load the pre-trained machine learning model
# model = joblib.load('/content/finalized_model.sav')
# 
# def predict(inputs):
#     # Make a prediction based on the inputs
#     prediction = model.predict(inputs)
#     return prediction[0]
# 
# 
# def app():
#     # Load the dataset
#     dataset = pd.read_csv('/content/diabetes.csv')
# 
#     # Define the user input widgets
#     input1 = st.number_input("Pregnancies")
#     input2 = st.number_input("Glucose")
#     input3 = st.number_input("BloodPressure")
#     input4 = st.number_input("SkinThickness")
#     input5 = st.number_input("Insulin")
#     input6 = st.number_input("BMI")
#     input7 = st.number_input("DiabetesPedigreeFunction")
#     input8 = st.number_input("Age")
#     # Create a button to make the prediction
#     
#     if st.button("Make Prediction"):
#         # Combine the user inputs into a single row of the dataset
#         input_row = pd.DataFrame({
#             'Pregnancies': [input1],
#             'Glucose': [input2],
#             'BloodPressure': [input3],
#             'SkinThickness': [input4],
#             'Insulin': [input5],
#             'BMI': [input6],
#             'DiabetesPedigreeFunction': [input7],
#             'Age': [input8]
#         })
# 
#         # Make a prediction based on the user inputs
#         prediction = predict(input_row)
# 
#         # Display the prediction to the user
#         if prediction==0:
#           st.write("A person has not diabetes:", prediction)
#         else :
#           st.write("A person has  diabetes:", prediction)
# if __name__ == '__main__':
#     st.set_page_config(page_title='My Streamlit App')
#     st.write('Hello, World!')
#     app()

!npm install localtunnel

!streamlit run /content/app.py &>/content/logs.txt &

!npx localtunnel --port 8501